package servidor.frames;

import java.awt.Color;
import java.awt.event.ActionEvent;
import java.io.IOException;
import servidor.aplicacao.Conexao;

public class FramePrincipal extends javax.swing.JFrame {

    Conexao conexao;
    
    public FramePrincipal() {
        initComponents();
        addListeners(); // chama a função que adiciona os listeners
    }

    private void addListeners(){
        btnIniciar.addActionListener((ActionEvent e) -> { // Evento de clique no botão iniciar
            lblStatus.setText("Iniciando...");
            lblStatus.setForeground(Color.yellow);
            txtLog.append("Iniciando servidor...\n");
            conexao = new Conexao(txtEndereco.getText(), Integer.parseInt(txtPorta.getText()));
            try {
                conexao.criarConexao();
            } catch (IOException ex) {
                ex.printStackTrace();
            }
            if(conexao.getStatus()){
                lblStatus.setText("Rodando");
                lblStatus.setForeground(Color.GREEN);
                btnIniciar.setEnabled(false);
                btnParar.setEnabled(true);
                txtEndereco.setEnabled(false);
                txtPorta.setEnabled(false);
                txtLog.append("Servidor iniciado com sucesso!\n");
            }
        });
        
        btnParar.addActionListener((ActionEvent e) -> {
            try {
                conexao.fecharConexao();
                lblStatus.setText("Parado");
                lblStatus.setForeground(Color.red);
                btnIniciar.setEnabled(true);
                btnParar.setEnabled(false);
                txtEndereco.setEnabled(true);
                txtPorta.setEnabled(true);
            } catch (IOException ex) {
                ex.printStackTrace();
            }
        });
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        pnlConexao = new javax.swing.JPanel();
        lblEndereco = new javax.swing.JLabel();
        txtEndereco = new javax.swing.JTextField();
        lblPorta = new javax.swing.JLabel();
        txtPorta = new javax.swing.JTextField();
        btnIniciar = new javax.swing.JButton();
        btnParar = new javax.swing.JButton();
        lblStatus = new javax.swing.JLabel();
        pnlInfo = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtLog = new javax.swing.JTextArea();
        lblUsuarios = new javax.swing.JLabel();
        lblUsuariosConectados = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Servidor");
        setName("frmPrincipal"); // NOI18N
        getContentPane().setLayout(new java.awt.GridBagLayout());

        pnlConexao.setBorder(javax.swing.BorderFactory.createTitledBorder("Conexão"));
        pnlConexao.setLayout(new java.awt.GridBagLayout());

        lblEndereco.setText("Endereço");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(20, 20, 5, 5);
        pnlConexao.add(lblEndereco, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 200;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(20, 5, 5, 5);
        pnlConexao.add(txtEndereco, gridBagConstraints);

        lblPorta.setText(":");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(20, 5, 5, 5);
        pnlConexao.add(lblPorta, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 50;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(20, 5, 5, 20);
        pnlConexao.add(txtPorta, gridBagConstraints);

        btnIniciar.setText("Iniciar");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 20, 5);
        pnlConexao.add(btnIniciar, gridBagConstraints);

        btnParar.setText("Parar");
        btnParar.setEnabled(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 20, 20);
        pnlConexao.add(btnParar, gridBagConstraints);

        lblStatus.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblStatus.setForeground(new java.awt.Color(255, 0, 0));
        lblStatus.setText("Parado");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(5, 20, 20, 5);
        pnlConexao.add(lblStatus, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(20, 20, 5, 20);
        getContentPane().add(pnlConexao, gridBagConstraints);

        pnlInfo.setBorder(javax.swing.BorderFactory.createTitledBorder("Informações"));
        pnlInfo.setLayout(new java.awt.GridBagLayout());

        jScrollPane1.setMaximumSize(new java.awt.Dimension(170, 100));
        jScrollPane1.setMinimumSize(new java.awt.Dimension(170, 100));
        jScrollPane1.setPreferredSize(new java.awt.Dimension(170, 100));

        txtLog.setEditable(false);
        txtLog.setColumns(20);
        txtLog.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        txtLog.setRows(5);
        txtLog.setToolTipText("");
        txtLog.setMaximumSize(new java.awt.Dimension(170, 100));
        txtLog.setMinimumSize(new java.awt.Dimension(170, 100));
        txtLog.setName(""); // NOI18N
        txtLog.setPreferredSize(new java.awt.Dimension(170, 100));
        jScrollPane1.setViewportView(txtLog);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(20, 20, 5, 20);
        pnlInfo.add(jScrollPane1, gridBagConstraints);

        lblUsuarios.setText("Usuários conectados:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(5, 20, 20, 5);
        pnlInfo.add(lblUsuarios, gridBagConstraints);

        lblUsuariosConectados.setText("0");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 20, 20);
        pnlInfo.add(lblUsuariosConectados, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(5, 20, 20, 20);
        getContentPane().add(pnlInfo, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIniciar;
    private javax.swing.JButton btnParar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblEndereco;
    private javax.swing.JLabel lblPorta;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JLabel lblUsuarios;
    private javax.swing.JLabel lblUsuariosConectados;
    private javax.swing.JPanel pnlConexao;
    private javax.swing.JPanel pnlInfo;
    private javax.swing.JTextField txtEndereco;
    private javax.swing.JTextArea txtLog;
    private javax.swing.JTextField txtPorta;
    // End of variables declaration//GEN-END:variables

}
